name: Bug Report
description: Report a bug or unexpected behavior in Visitas
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us investigate the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        Example: When I tap on a visit entry, the app crashes instead of opening the details screen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Open the app
        2. Navigate to '...'
        3. Tap on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example: The visit details screen should open showing the visit information.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: |
        Example: The app crashes with a blank screen and returns to the home screen.
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: "Example: Samsung Galaxy S24, Pixel 8"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android is the device running?
      placeholder: "Example: Android 15"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Visitas are you using?
      placeholder: "Example: 1.2.0"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: If applicable, add screenshots or screen recordings to help explain the issue.
      placeholder: |
        You can attach images or recordings by dragging and dropping them here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
