name: Feature Request
description: Suggest a new feature or enhancement for Visitas
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the information below.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Describe the problem or need this feature would address. Why is this feature important?
      placeholder: "I'm frustrated when... / It would be helpful if... / Users need..."
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
      placeholder: "I would like to see... / The feature should... / This could work by..."
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried... / Another approach could be..."
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: "Screenshots, mockups, examples, or any other relevant information..."
    validations:
      required: false
